# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotfiles < Formula
  desc "A tool help setup your dotfiles"
  homepage "https://github.com/bottlerocketlabs/dotfiles"
  version "0.0.5"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bottlerocketlabs/dotfiles/releases/download/v0.0.5/dotfiles_0.0.5_Darwin_x86_64.tar.gz"
    sha256 "108965d10fdf7f059efe24bee31f32073f19812f0ddfc516e7eca9ded7db8bbf"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bottlerocketlabs/dotfiles/releases/download/v0.0.5/dotfiles_0.0.5_Linux_x86_64.tar.gz"
    sha256 "fece83b9374b3131bfffedb1a63bc0e635b01eb682ad0e51f1a308397444b6d5"
  end

  depends_on "go"

  def install
    bin.install "dotfiles"
  end

  test do
    system "#{bin}/dotfiles -help"
  end
end
