# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotfiles < Formula
  desc "A tool help setup your dotfiles"
  homepage "https://github.com/bottlerocketlabs/dotfiles"
  version "0.1.1"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bottlerocketlabs/dotfiles/releases/download/v0.1.1/dotfiles_0.1.1_Darwin_amd64.tar.gz"
    sha256 "fb10ef2d145d235ab0cf71237d59713fff7b47168ae9ad24c14f6a7f4b296dd0"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bottlerocketlabs/dotfiles/releases/download/v0.1.1/dotfiles_0.1.1_Linux_amd64.tar.gz"
    sha256 "c12d228cb334975654d27fc1f5e472e91312191a31804ae4150797e829fb45c1"
  end

  depends_on "go"

  def install
    bin.install "dotfiles"
  end

  test do
    system "#{bin}/dotfiles -help"
  end
end
