# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitlab < Formula
  desc "Create gitlab issue in project linked to current git repository using git editor and selecting optional template"
  homepage "https://github.com/bottlerocketlabs/gitlab"
  version "0.0.2"
  license "BSD-3-clause"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bottlerocketlabs/gitlab/releases/download/v0.0.2/gitlab_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "04b4bf0d1d77f8e42efd02533bba763390a92b733272a0798be49ef22336392e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bottlerocketlabs/gitlab/releases/download/v0.0.2/gitlab_0.0.2_Linux_x86_64.tar.gz"
    sha256 "f74c67337efe036fa4619530271142210251d3fdca23d72fbfa0b5d6783a3d02"
  end

  depends_on "go"

  def install
    bin.install "gitlab"
  end

  test do
    system "#{bin}/gitlab -help"
  end
end
