# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitlab < Formula
  desc "Create gitlab issue in project linked to current git repository using git editor and selecting optional template"
  homepage "https://github.com/bottlerocketlabs/gitlab"
  version "0.1.1"
  license "BSD-3-clause"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bottlerocketlabs/gitlab/releases/download/v0.1.1/gitlab_0.1.1_Darwin_amd64.tar.gz"
    sha256 "962389b87bbb6352dcc607d7e00ae319ac28227890a04298505a1a4b537b6999"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bottlerocketlabs/gitlab/releases/download/v0.1.1/gitlab_0.1.1_Linux_amd64.tar.gz"
    sha256 "77fdaab69ce1261ff0f6e7b6ea273b4cacdc714721721099b9653bad0fec7048"
  end

  depends_on "go"

  def install
    bin.install "gitlab"
  end

  test do
    system "#{bin}/gitlab -help"
  end
end
