# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitlab < Formula
  desc "Create gitlab issue in project linked to current git repository using git editor and selecting optional template"
  homepage "https://github.com/bottlerocketlabs/gitlab"
  version "0.1.3"
  license "BSD-3-clause"

  if OS.mac?
    url "https://github.com/bottlerocketlabs/gitlab/releases/download/v0.1.3/gitlab_0.1.3_Darwin_amd64.tar.gz"
    sha256 "8d66f065d51597584c968b3fd618c7b55ea9a09bc43162e06aa5283fa81dd5f9"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bottlerocketlabs/gitlab/releases/download/v0.1.3/gitlab_0.1.3_Linux_amd64.tar.gz"
    sha256 "6994a8c178b3e66b00c168d202f65828d937c1ad9e7a4d370ba06d0216f8eef6"
  end

  depends_on "go"

  def install
    bin.install "gitlab"
  end

  test do
    system "#{bin}/gitlab -h"
  end
end
