# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Localpod < Formula
  desc "A tool help local development environments"
  homepage "https://github.com/bottlerocketlabs/localpod"
  version "0.0.10"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bottlerocketlabs/localpod/releases/download/v0.0.10/localpod_0.0.10_Darwin_x86_64.tar.gz"
    sha256 "ab1f9810a8a61c547a7793eb8c2f5d272c7da4d6519da1eff0c806cc0ab6ba92"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bottlerocketlabs/localpod/releases/download/v0.0.10/localpod_0.0.10_Linux_x86_64.tar.gz"
    sha256 "6c5c0321fbd60d1b8dfd2ca83c30d05bd23ed8a17645a1d518fbef28dbd283ff"
  end

  depends_on "go"

  def install
    bin.install "localpod"
  end

  test do
    system "#{bin}/localpod -help"
  end
end
