# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pair < Formula
  desc "A tool for pair programming"
  homepage "https://github.com/bottlerocketlabs/pair"
  version "0.1.0"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bottlerocketlabs/pair/releases/download/v0.1.0/pair_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "8ad627584aeddbd0d7a3d1442ff40c4bdb87f82cf79d619477acb1ea0365d905"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bottlerocketlabs/pair/releases/download/v0.1.0/pair_0.1.0_Linux_x86_64.tar.gz"
    sha256 "c3651688948eb0188837a0b1e7c0ee41fc3365596e9c0ef5db7e1922a3550d18"
  end

  depends_on "go"

  def install
    bin.install "pair"
    bin.install "pair-server"
    bin.install "pair-server-simple"
  end

  test do
    system "#{bin}/pair -version"
  end
end
