# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pair < Formula
  desc "A tool for terminal based pair programming"
  homepage "https://github.com/bottlerocketlabs/pair"
  version "0.1.4"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bottlerocketlabs/pair/releases/download/v0.1.4/pair_0.1.4_Darwin_amd64.tar.gz"
    sha256 "8b2e2281d75db23b7fb78aa863d16bf607b00fe6465e1759bc920d5f1b5051c3"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bottlerocketlabs/pair/releases/download/v0.1.4/pair_0.1.4_Linux_amd64.tar.gz"
    sha256 "23a9394b6322173c5b565a53e8d83a13042a8dd761fb162a60b165f9d24e7d03"
  end

  depends_on "go"

  def install
    bin.install "pair"
    bin.install "pair-server"
    bin.install "pair-server-simple"
  end

  test do
    system "#{bin}/pair -version"
  end
end
