# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pair < Formula
  desc "A tool for terminal based pair programming"
  homepage "https://github.com/bottlerocketlabs/pair"
  version "0.1.2"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bottlerocketlabs/pair/releases/download/v0.1.2/pair_0.1.2_Darwin_amd64.tar.gz"
    sha256 "77cde27f3a87c701803e0f34e84100086a3d0ce95f9874a36c99dcaebc6e7984"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bottlerocketlabs/pair/releases/download/v0.1.2/pair_0.1.2_Linux_amd64.tar.gz"
    sha256 "e246b5b445c8ef3333fb7c70f1cecaefa0955e833f6447097e8bb3831d70be2a"
  end

  depends_on "go"

  def install
    bin.install "pair"
    bin.install "pair-server"
    bin.install "pair-server-simple"
  end

  test do
    system "#{bin}/pair -version"
  end
end
