# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pbcopy < Formula
  desc "pbcopy for linux that works in the terminal over ssh"
  homepage "https://github.com/bottlerocketlabs/remote-pbcopy"
  version "0.0.9"
  license "MIT"
  bottle :unneeded
  depends_on :linux

  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bottlerocketlabs/remote-pbcopy/releases/download/v0.0.9/remote-pbcopy_0.0.9_Linux_x86_64.tar.gz"
    sha256 "5fcfaf44e434ee0b10bc2189eff3bd1d43332dec438a29b290d4e45ca41e381f"
  end

  depends_on "go"

  def install
    bin.install "pbcopy"
  end

  test do
    system "#{bin}/pbcopy -h"
  end
end
