# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pbcopy < Formula
  desc "pbcopy for linux that works in the terminal over ssh"
  homepage "https://github.com/stuart-warren/remote-pbcopy"
  version "0.0.8"
  license "MIT"
  bottle :unneeded
  depends_on :linux

  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bottlerocketlabs/remote-pbcopy/releases/download/v0.0.8/remote-pbcopy_0.0.8_Linux_x86_64.tar.gz"
    sha256 "1719ff849473961390849f4fc1f1589c9971e6868618eb3846da2b8538f95b4f"
  end

  depends_on "go"

  def install
    bin.install "pbcopy"
  end

  test do
    system "#{bin}/pbcopy -h"
  end
end
