# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pbcopy < Formula
  desc "pbcopy for linux that works in the terminal over ssh"
  homepage "https://github.com/bottlerocketlabs/remote-pbcopy"
  version "0.0.10"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bottlerocketlabs/remote-pbcopy/releases/download/v0.0.10/remote-pbcopy_0.0.10_Darwin_x86_64.tar.gz"
    sha256 "a8ecdacbfb686d0bca645548b6ec0fb3a83a97962e1716398e8095762644485c"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bottlerocketlabs/remote-pbcopy/releases/download/v0.0.10/remote-pbcopy_0.0.10_Linux_x86_64.tar.gz"
    sha256 "1856321b605ffa2d5e3f8fda07b32fe349e9ff9cc31d30da55f12f0443feaa55"
  end

  depends_on "go"

  def install
    bin.install "pbcopy"
  end

  test do
    system "#{bin}/pbcopy -h"
  end
end
