# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rpbcopy < Formula
  desc "rpbcopy for linux that works in the terminal over ssh"
  homepage "https://github.com/bottlerocketlabs/remote-pbcopy"
  version "0.1.2"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bottlerocketlabs/remote-pbcopy/releases/download/v0.1.2/rpbcopy_0.1.2_Darwin_amd64.tar.gz"
    sha256 "a294f2af16bba957ba43022bfb2e00b8988d4199afd89f575f987fa95b7ab594"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bottlerocketlabs/remote-pbcopy/releases/download/v0.1.2/rpbcopy_0.1.2_Linux_amd64.tar.gz"
    sha256 "50ca1ef46acc8da03dfc91dbf737ed2690b586866ed71f47fcbf919a1161d485"
  end

  depends_on "go"

  def install
    bin.install "rpbcopy"
  end

  test do
    system "#{bin}/rpbcopy -h"
  end
end
